### ISSUE TITLE
Exceptions not propagated to caller, causing it to be suspended in limbo

### ISSUE THREAD

**Issue by arvidfm** [odrling/peony-twitter#17]
Whenever an API call fails (e.g. from a `DoesNotExist` exception), the caller will never be resumed, because the exception is never set on the returned `Request` object (should be done e.g. at the end of `BasePeonyClient.request`). This prevents idioms such as:

```py
try:
    await twitter.api.lists.show.get(slug="invalid_list", owner_screen_name="someuser")
except peony.exceptions.DoesNotExist:
    # handle error
    print("The provided list does not exist!")
```

and will generally cause confusion when coroutines randomly fail to be resumed. This can be fixed by defining the following error handler:

```py
def error_handler(request):
    async def handler(future, **kwargs):
        try:
            await request(future=future, **kwargs)
        except Exception as e:
            future.set_exception(e)
    return handler
```

I think it would be preferable if exceptions were always propagated to the caller by default, or at least the documentation should include an example on how to do it.

**Comment by odrling** [comment]
I will probably add a future parameter to `exceptions.throw` and `data_processing.read` and call set_exception there.

Another way to fix this bug would be to find a way to use coroutines internally instead of a future but I might have to change more things.

**Comment by odrling** [comment]
So it turns out that I couldn't use `set_exception` in `BasePeonyClient.request` because then this would bypass the error handle and raise all the exceptions that it encounters (the error handler is just a decorator for the `request` method).

So instead I made a new default error handler that will call `set_exception` when required. Now the error handler is a class (`ErrorHandler`) which can be inherited from to change its behavior.
You have to use `@ErrorHandler.handle` to change the behavior of the error handle when it receives an exception, the decorated method must return `ErrorHandler.RETRY` if you want to retry the request (by default it will raise the exception if the function returns None).

It seems like the build fails on earlier versions of Python 3.5 for now but it seems to work fine.

**Comment by odrling** [comment]
This should now be fixed and these changes are included in the new release.
