### ISSUE TITLE
Add extra error codes

### ISSUE THREAD

**Issue by boulderwebdev** [odrling/peony-twitter#32]
I noticed there are some out of date and non-existent [error codes](https://developer.twitter.com/en/docs/basics/response-codes) in the `exceptions.py` file. This includes
* 3 - Invalid coordinates
* 13 - No location associated with the specified IP address.
* 17 - No user matches for specified terms.
* 36 - You cannot report yourself for spam.
* 38 - <named> parameter is missing.
* 44 - attachment_url parameter is invalid
* 50 - User not found.
* 63 - User has been suspended.
* 87 - Client is not permitted to perform this action.
* 89 - Invalid or expired token
* 93 - This application is not allowed to access or delete your direct messages
* 99 - Unable to verify your credentials.
* 120 - Account update failed: value is too long (maximum is nn characters).
* 139 - You have already favorited this status.
* 144 - No status found with that ID.
* 150 - You cannot send messages to users who are not following you.
* 151 - There was an error sending your message: reason
* 160 - You've already requested to follow user.
* 186 - Tweet needs to be a bit shorter.
* 195 - Missing or invalid url parameter
* 205 - You are over the limit for spam reports.
* 214 - Owner must allow dms from anyone.	
* 220 - Your credentials do not allow access to this resource.
* 323 - Animated GIFs are not allowed when uploading multiple images.
* 324 - The validation of media ids failed.
* 325 - A media id was not found.
* 326 - To protect our users from spam and other malicious activity, this account is temporarily locked.
* 327 - You have already retweeted this Tweet.
* 349 - You cannot send messages to this user.
* 355 - Subscription already exists.
* 385 - You attempted to reply to a Tweet that is deleted or not visible to you.
* 386 - The Tweet exceeds the number of allowed attachment types.
* 407 - The given URL is invalid.
* 415 - Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
* 416 - Invalid / suspended application
* 417 - Desktop applications only support the oauth_callback value 'oob'
* 421 - This Tweet is no longer available
* 422 - This Tweet is no longer available because it violated the Twitter Rules.
* 433 - The original Tweet author restricted who can reply to this Tweet.

### out of date
These are also exceptions no longer part of Twitter's documentation

* 136 - Blocked
* 231 - VerifyLogin

Also, status code 415 is no longer returned by Twitter.

**Comment by odrling** [comment]
Hi! Thank you for reporting this issue, I'll update the exceptions ASAP.

**Comment by odrling** [comment]
That last commit should have added the error codes (and the exception for status code 409 which is only mentioned as the status code corresponding to the error code 355). 

I've made all the exception inherit from the exception from the corresponding status code so that existing code that would rely on these exceptions (like `Forbidden`) instead of the exceptions for the new error codes will still work.
The downside in this change is that it still introduces a breaking change, if you used both kinds of exceptions in your code, now the exception related to the error codes will be caught with an `except` for their corresponding status code.
To make sure that this never happens in your code, exceptions related to the status code should be caught **after** the ones related to the error code:

```python
except ReadOnlyApplication:
    pass
except Forbidden:
    pass
```

I think there should be an easy way to tell if the exception is related to the HTTP code or to the Twitter error code. 
Right now I'm thinking about changing the names of the status code exceptions to add `HTTP` as a prefix. So `Forbidden` would become `HTTPForbidden`.
This will make it clear that it is related to the HTTP error code and when updating peony Python will crash because it won't find the exception with the name that was used in previous versions.
I believe this would make the update slightly easier since python will tell you by itself where it can't find the exception you were using which sounds better to me than your code suddenly running differently because of some obscure change in the library.

**Comment by DarkWingMcQuack** [comment]
For me twitter still returns code 136 as well as code 162 like this:
```
{'errors': 
  [
    {
      'code': 136, 'message': "You have been blocked from retweeting this user's tweets at their request."
    }
  ]
}
```
```
{'errors': 
  [
    {
      'code': 162, 'message': 'You have been blocked from following this account at the request of the user.'
    }
  ]
}
```
