### ISSUE TITLE
V2 support

### ISSUE THREAD

**Issue by 11qu1d** [odrling/peony-twitter#45]
With the most recent depreciation of the v1.1 endpoints for posting, is there a plan to update this library to support v2 management of tweets (posting, deleting, etc.).

Many thanks

**Comment by odrling** [comment]
Peony already supports API v2 with a few arguments when instanciating the client. In fact my last commit was adding examples to use API v2 ae28b35f74ccf26cb2306b82b9e7af749e6a3a02.
I'm a bit reluctant to change the default but it probably will happen with a bump to v3.0.0.

To use the streaming endpoints you will need f56069e9427dc291f6fcb356fa10b02eb4b45e63, which is not yet in the latest release as it is not in the documentation (but it is used in [one of the examples](https://github.com/odrling/peony-twitter/blob/ae28b35f74ccf26cb2306b82b9e7af749e6a3a02/examples/track_apiv2.py)).

So, if you need the streaming endpoints you should install Peony from this git repository rather than using the package from Pypi, otherwise the latest release should work fine with the REST endpoints.

**Comment by 11qu1d** [comment]
I see, I was looking at the release notes and must have missed the latest commits. Thank you for your help.
