### ISSUE TITLE
RateLimitExceeded is not raised, handled

### ISSUE THREAD

**Issue by osamak** [odrling/peony-twitter#9]
According to [Twitter docs](https://dev.twitter.com/overview/api/response-codes), when the rate limit is exceeded HTTP status code 429 ("Too many requests") is raised with a Twitter code error 88 ("Rate limit exceeded").

Currently, peony depends on HTTP status codes to raise exceptions, so exceeding the rate limit would correctly raise `exceptions.TooManyRequests`, but only `exceptions.RateLimitExceeded` is being handled by the default `error_handler`.

To my knowledge, `exceptions.RateLimitExceeded`, being an internal Twitter code error (rather than an HTTP status code) shouldn't be an exception, and it shouldn't be handled.  Instead, `exceptions.TooManyRequests` should be.

The default `error_handler` should handle `exceptions.TooManyRequests` instead of `exceptions.RateLimitExceeded` (or maybe with it?)

**Comment by odrling** [comment]
Peony should relies on error codes to raise a corresponding exception, if it couldn't find the error code then it will raise an exception corresponding to the HTTP status of the response, if no exception was found for the status code it should raise a `PeonyException` (and I hope somebody would open an issue for this)

Error codes should raise an exception, otherwise some programs would raise some other weird exceptions instead. Users should know just when their code went wrong and not get an exception for something that was wrong 20 lines above.

```python
data = await client.endpoint.get()  # let's say this is a request to an actual endpoint
data.text  # if an error occurred for the request this would raise an AttributeError
           # which doesn't really explains what was wrong
```

Is there an endpoint that returns a 429 status code but no error code with [the contextual headers that are used by `TooManyRequests`](https://dev.twitter.com/rest/public/rate-limiting#http-headers-and-response-codes)?

**Comment by odrling** [comment]
Well, that probably won't change, the only endpoint I know that would return a 429 status code without the error code are in the streaming API and they don't return these contextual headers.
